# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ln_Im2wDXeR4kL3ICzVKQVxXy-l_vC8y
"""

from google.colab import files
from google.colab.patches import cv2_imshow
import cv2
import numpy as np
import matplotlib.pyplot as plt
upload=files.upload()
image_path=list(upload.keys())[0]

def preprocess_image(image_path):
  image=cv2.imread(image_path)
  gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
  gray=cv2.medianBlur(gray, 5)
  return (image,gray)

def detect_circles(gray):
  print("Adjust Paramters; press Enter to use default set values")
  dp=input("Enter dp value (Inverse ratio of accumulator resolution; default value: 1): ")
  if dp:
    dp=float(dp)
  else:
    dp=1
  minDist=input("Enter minDist value (Minimum distance between circle centers; default value: 50): ")
  if minDist:
    minDist=int(minDist)
  else:
    minDist=50
  param1=input("Enter param1 value (Upper threshold for Canny edge detector; default value: 50): ")
  if param1:
    param1=int(param1)
  else:
    param1=50
  param2=input("Enter param2 value (Accumulator threshold (lower = more circles); default value: 30): ")
  if param2:
    param2=int(param2)
  else:
    param2=30
  minRadius=input("Enter minRadius value (Size constraints; default value: 10): ")
  if minRadius:
    minRadius=int(minRadius)
  else:
    minRadius=10
  maxRadius=input("Enter maxRadius value (Size constraints; default value: 100): ")
  if maxRadius:
    maxRadius=int(maxRadius)
  else:
    maxRadius=100
  circles = cv2.HoughCircles(gray, cv2.HOUGH_GRADIENT, dp=dp, minDist=minDist, param1=param1, param2=param2, minRadius=minRadius, maxRadius=maxRadius)
  return circles

def visualize_circles(image, circles, save_path=None):
  annotated_image=image.copy()
  if circles is None:
    print("No circles found")
  else:
    circles= np.uint16(np.around(circles))
    id=1
    for i in circles[0,:]:
      x,y,r=i
      cv2.circle(annotated_image,(x,y),r,(0,255,0),2)
      cv2.circle(annotated_image,(x,y),2,(0,0,255),2)
      txt1=f"ID:{id}"
      txt2=f"Radius={r}"
      cv2.putText(annotated_image,txt1 , (x - 20, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1)
      cv2.putText(annotated_image,txt2 , (x - 20, y + 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1)
      id+=1
  save_image=input("Save annotated image file?(y/n)")
  if save_image=="y":
    save_path=input("Enter filename with extension")
    cv2.imwrite(save_path,annotated_image)
    print("Image saved")
  else:
    print("Image not saved")
  fig, axes = plt.subplots(1, 2, figsize=(10, 10))
  axes[0].imshow(image)
  axes[0].set_title('Original Image')
  axes[0].axis("off")
  axes[1].imshow(annotated_image)
  axes[1].set_title('Annotated Image')
  axes[1].axis("off")
  print("Displaying Original Image and Annotated Image")
  plt.show()

def calculate_statistics(circles):
  mean_radius=np.mean(circles[0,:,2])
  min_radius=np.min(circles[0,:,2])
  max_radius=np.max(circles[0,:,2])
  file=open("statistics.txt","w")
  file.write(f"Total Number of circles detected: {len(circles[0,:])}\n")
  file.write(f"Mean radius: {mean_radius}\n")
  file.write(f"Min radius: {min_radius}\n")
  file.write(f"Max radius: {max_radius}\n")
  file.write("Coordinates and Radii: \n")
  id=1
  d={}
  d["Average Radius"]=mean_radius
  d["Minimum Radius"]=min_radius
  d["Maximum Radius"]=max_radius
  d["Total Number of Circles"]=len(circles[0,:])
  for i in circles[0,:]:
    x,y,r=i
    d[id]=[(x,y),r]
    file.write(f"{id} -> ({x},{y}) : radius={r} \n")
    id+=1
  file.close()
  print("Statistics saved to text file")
  save_file=input("Download statistics file? (y/n)")
  if save_file=="y":
    files.download("statistics.txt")
  else:
    print("File not downloaded")
  print("Displaying dictionary with statistics")
  print(d)

def main():
  image,gray=preprocess_image(image_path)
  circles=detect_circles(gray)
  calculate_statistics(circles)
  visualize_circles(image, circles, save_path=None)

if __name__ == "__main__":
    main()